<a href="https://colab.research.google.com/github/sener7106/TiL/blob/main/DL20220215.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import tensorflow as tf

In [3]:
data = datasets.load_breast_cancer()

In [4]:
X = data.data

In [5]:
y = data.target

In [6]:
X_train, X_test , y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler.fit(X_train)


StandardScaler()

In [8]:
X_train = scaler.transform(X_train)

In [9]:
model = Sequential()
model.add(Dense(1, input_dim = 30, activation = 'sigmoid'))

In [10]:
model.summary

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 31        
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.compile(loss = 'binary_crossentropy', optimizer = Adam(learning_rate = 0.001), metrics = ['acc'])

In [16]:
model.fit(X_train, y_train, epochs = 1000)

Epoch 1/1000
15/15 [==============================] - 3s 7ms/step - loss: 0.6994 - acc: 0.5780
Epoch 2/1000
15/15 [==============================] - 0s 6ms/step - loss: 0.6299 - acc: 0.6681
Epoch 3/1000
15/15 [==============================] - 0s 8ms/step - loss: 0.5717 - acc: 0.7231
Epoch 4/1000
15/15 [==============================] - 0s 6ms/step - loss: 0.5238 - acc: 0.7670
Epoch 5/1000
15/15 [==============================] - 0s 5ms/step - loss: 0.4839 - acc: 0.7978
Epoch 6/1000
15/15 [==============================] - 0s 5ms/step - loss: 0.4491 - acc: 0.8154
Epoch 7/1000
15/15 [==============================] - 0s 4ms/step - loss: 0.4197 - acc: 0.8352
Epoch 8/1000
15/15 [==============================] - 0s 6ms/step - loss: 0.3943 - acc: 0.8396
Epoch 9/1000
15/15 [==============================] - 0s 5ms/step - loss: 0.3732 - acc: 0.8549
Epoch 10/1000
15/15 [==============================] - 0s 6ms/step - loss: 0.3533 - acc: 0.8637
Epoch 11/1000
15/15 [============================

In [17]:
X_test = scaler.transform(X_test)

In [28]:
pred = model.predict(X_test)

In [30]:
predict01 = np.where(pred > 0.5, 1, 0)

In [33]:
predict01.flatten()

array([1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0])

In [34]:
np.sum((predict01.flatten() == y_test))

112

In [35]:
acc = 112 / 114

In [36]:
acc

0.9824561403508771

In [37]:
import numpy as np

In [39]:
X = np.array([[0., 0.],
              [0., 1.],
              [1., 0.],
              [1., 1.]])

In [41]:
y = np.array([[0.],
             [1.],
             [1.],
             [0.]]) 

In [42]:
y.shape

(4, 1)

In [43]:
w = np.array([[1], [2]], dtype = 'float32')
b = np.array([3], dtype = 'float32')

In [44]:
w

array([[1.],
       [2.]], dtype=float32)

In [45]:
b

array([3.], dtype=float32)

In [47]:
np.dot(X,w) + b

array([[3.],
       [5.],
       [4.],
       [6.]])

In [48]:
def sigmoid(h) :
  return 1 / (1 + np.exp(-h))

In [49]:
hyp = np.dot(X, w) + b 

In [56]:
#learning rate
learning_rate = 0.1

for i in range(1000) :
  for j in range(2) :
    hypothesis = sigmoid(np.dot(X, w) + b)
    print('예측값 : ', hypothesis)

    # 오차 계산
    cost = - 1 / 4 * (y * np.log(hypothesis) + (1 - y) * np.log(1 - hypothesis))
    print('cost : ', cost)
    # X의 줄, 칸을  변경하여 실행
    X_col_2d = X.T[j].reshape(1, -1)
    # gradient
    w_grad = 1 / 4 * np.sum(np.dot(X_col_2d, (hypothesis - y)))
    print('w_{}grad:{}'.format(i, w_grad))
    # update w
    w[j] = w[j] - learning_rate * w_grad
    print("w{} : {}".format(j, w))

    # gradient
    b_grad = 1 / 4 * np.sum(hypothesis - y)
    print('b_{}grad:{}'.format(i, b_grad))
    # update w
    b= b - learning_rate * b_grad
    print("b : {}".format(b))



스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 [0.17312238]
 [0.17364238]
 [0.17407522]]
w_807grad:0.00047582509866428424
w1 : [[0.00498169]
 [0.00909253]]
b_807grad:-0.00019086004667262513
b : [-0.00780526]
예측값 :  [[0.49804869]
 [0.50032182]
 [0.49929411]
 [0.50156724]]
cost :  [[0.17231304]
 [0.17312594]
 [0.17363999]
 [0.17407164]]
w_808grad:0.00021533580552657305
w0 : [[0.00496016]
 [0.00909253]]
b_808grad:-0.00019203630935829552
b : [-0.00778606]
예측값 :  [[0.4980535 ]
 [0.50032662]
 [0.49929353]
 [0.50156665]]
cost :  [[0.17231543]
 [0.17312354]
 [0.17364028]
 [0.17407135]]
w_808grad:0.00047331767740907416
w1 : [[0.00496016]
 [0.0090452 ]]
b_808grad:-0.00018992717178370477
b : [-0.00776707]
예측값 :  [[0.49805824]
 [0.50031953]
 [0.49929827]
 [0.50155957]]
cost :  [[0.1723178 ]
 [0.17312708]
 [0.1736379 ]
 [0.1740678 ]]
w_809grad:0.00021446043719106078
w0 : [[0.00493871]
 [0.0090452 ]]
b_809grad:-0.00019109540178921525
b : [-0.00774796]
예측값 :  [[0.49806302]
 [0.50032431]
 [0.49929769]
 [0.50155

In [57]:
w

array([[0.00213039],
       [0.0033576 ]], dtype=float32)

In [58]:
b

array([-0.00304319], dtype=float32)

In [59]:
pred = sigmoid(np.dot(X, w) + b)

In [60]:
pred

array([[0.4992392],
       [0.5000786],
       [0.4997718],
       [0.5006112]])

In [61]:
pred01 = np.where(pred > 0.5, 1, 0)

In [62]:
pred01

array([[0],
       [1],
       [0],
       [1]])

In [63]:
predict02 = (pred01 == y)

In [64]:
np.sum(predict02)

2

In [65]:
acc = np.sum(predict02) / 4

In [66]:
acc

0.5