<a href="https://colab.research.google.com/github/sener7106/TiL/blob/main/DL_20220214.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [99]:
%tensorflow_version 1.x

In [100]:
import numpy as np
import tensorflow as tf

In [101]:
tf.enable_eager_execution()
print(tf.__version__)

1.15.2


In [102]:
# AND 연산의 x1, x2의 입력을 저장

X = np.array([[0.,  0.],
              [0., 1.],
              [1., 0.],
               [1., 1.]], dtype = 'float32')

In [103]:
y = np.array([
              [0.],
              [0.],
              [0.],
              [1.]
], dtype = 'float32')

In [104]:
w = tf.Variable([[1],[2]], dtype = 'float32')
b = tf.Variable([3], dtype = "float32")

In [105]:
# X와 w의 곱을 계산
tf.matmul(X, w) 

<tf.Tensor: id=78045, shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [2.],
       [1.],
       [3.]], dtype=float32)>

In [106]:
# tf.matmul (X, w) + b
hypothesis = tf.sigmoid(tf.matmul(X, w) + b)

In [107]:
# W와 b값을 자동으로 수정
optimizer = tf.train.AdamOptimizer(0.01)

In [108]:
for step in range(5000) :
  with tf.GradientTape() as tape :
    hypothesis = tf.sigmoid(tf.matmul(X, w) + b)
    cost = -tf.reduce_mean(y * tf.log(hypothesis) + (1 - y) * tf.log(1 - hypothesis))
    # cost W, b를 이용하여 W의 기울기, b의 기울기를 계산해서 grad에 대입
    grads = tape.gradient(cost, [w,b])
    optimizer.apply_gradients(grads_and_vars = zip(grads, [w, b]))


  if step % 100 == 0 :
    print("=" * 40)
    print("step : {}, cost: {}, w : {}, b{}".format(step, cost, w.numpy(), b.numpy()))
    print("=" * 40)

step : 0, cost: 3.0189826488494873, w : [[0.99]
 [1.99]], b[2.99]
step : 100, cost: 1.852928876876831, w : [[0.01112575]
 [1.001489  ]], b[2.0029898]
step : 200, cost: 1.0872457027435303, w : [[-0.7114206 ]
 [ 0.18463652]], b[1.1350006]
step : 300, cost: 0.8457093834877014, w : [[-0.7703851 ]
 [-0.11182875]], b[0.5257181]
step : 400, cost: 0.7202606201171875, w : [[-0.45110112]
 [-0.03789831]], b[0.06198941]
step : 500, cost: 0.6177883148193359, w : [[-0.07153893]
 [ 0.1627059 ]], b[-0.35743272]
step : 600, cost: 0.5337925553321838, w : [[0.27751854]
 [0.39751327]], b[-0.7549591]
step : 700, cost: 0.4659406244754791, w : [[0.58535916]
 [0.6383078 ]], b[-1.1313305]
step : 800, cost: 0.41105541586875916, w : [[0.8586161]
 [0.8750349]], b[-1.4864284]
step : 900, cost: 0.36615604162216187, w : [[1.1055079]
 [1.103506 ]], b[-1.8219206]
step : 1000, cost: 0.32885342836380005, w : [[1.332784 ]
 [1.3223376]], b[-2.1403058]
step : 1100, cost: 0.29735806584358215, w : [[1.5453968]
 [1.5316243]],

In [109]:
w

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[7.0477467],
       [7.0392036]], dtype=float32)>

In [110]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-10.636643], dtype=float32)>

In [111]:
predict = tf.sigmoid(tf.matmul(X, w) + b)
predict

<tf.Tensor: id=393311, shape=(4, 1), dtype=float32, numpy=
array([[2.4018951e-05],
       [2.6663357e-02],
       [2.6885968e-02],
       [9.6924031e-01]], dtype=float32)>

In [112]:
predict01 = tf.cast(predict > 0.5 , dtype = tf.float32)
print("===================")
print("predict01")
print(predict01)

predict01
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [1.]], shape=(4, 1), dtype=float32)


In [113]:
# tf.equal(predict, y_data) : 조건을 만족하면 true or False 리턴

ac01 = tf.equal(predict01, y)
ac01

<tf.Tensor: id=393316, shape=(4, 1), dtype=bool, numpy=
array([[ True],
       [ True],
       [ True],
       [ True]])>

In [114]:
# tf.cast() = bool -> float

ac02 = tf.cast(ac01, dtype = 'float32')
ac02

<tf.Tensor: id=393317, shape=(4, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.],
       [1.]], dtype=float32)>

In [115]:
ac03 = tf.reduce_mean(ac02)
ac03

<tf.Tensor: id=393319, shape=(), dtype=float32, numpy=1.0>

In [116]:
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, y), dtype = tf.float32))
print("=======")
print("accuracy")
print(accuracy.numpy())

accuracy
1.0


In [117]:
# 0, 1 의 and 연산 실행
arr = np.array([[0,1]], dtype = "float32")

predict = tf.sigmoid(tf.matmul(arr, w) + b)
predict

<tf.Tensor: id=393330, shape=(1, 1), dtype=float32, numpy=array([[0.02666336]], dtype=float32)>

In [118]:
predict = tf.cast(predict > 0.5 , dtype = tf.float32)
predict.numpy()

array([[0.]], dtype=float32)

In [119]:
# tensorflow keras

In [120]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import numpy as np

In [121]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [122]:
y

array([[0.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [123]:
# 입력값을 읽어서 예측
model = Sequential()
# model 에 데이터 분석 객체를 추가

# Dense(1, input_dim = 2, activation = sigmoid)
# Dense : 선형회귀를 수행할 객체

model.add(Dense(1, input_dim = 2, activation = 'sigmoid'))

# 예측값을 hypothesis에 대입
#hypothesis = sigmoid(np.dot(X,w) + b)

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [124]:
model.compile(loss = 'binary_crossentropy', optimizer = Adam(lr = 0.1), metrics = ['acc'])

In [125]:
model.fit(X, y, epochs = 100)

Train on 4 samples
Epoch 1/100
4/4 [==============================] - 0s 58ms/sample - loss: 0.7897 - acc: 0.7500
Epoch 2/100
4/4 [==============================] - 0s 1ms/sample - loss: 0.7574 - acc: 0.7500
Epoch 3/100
4/4 [==============================] - 0s 1ms/sample - loss: 0.7261 - acc: 0.7500
Epoch 4/100
4/4 [==============================] - 0s 515us/sample - loss: 0.6959 - acc: 0.7500
Epoch 5/100
4/4 [==============================] - 0s 642us/sample - loss: 0.6669 - acc: 0.7500
Epoch 6/100
4/4 [==============================] - 0s 605us/sample - loss: 0.6390 - acc: 0.7500
Epoch 7/100
4/4 [==============================] - 0s 680us/sample - loss: 0.6123 - acc: 0.7500
Epoch 8/100
4/4 [==============================] - 0s 851us/sample - loss: 0.5867 - acc: 0.7500
Epoch 9/100
4/4 [==============================] - 0s 514us/sample - loss: 0.5624 - acc: 0.7500
Epoch 10/100
4/4 [==============================] - 0s 604us/sample - loss: 0.5393 - acc: 0.7500
Epoch 11/100
4/4 [=======

In [126]:
pred = model.predict(X)
pred

array([[0.00129294],
       [0.0842823 ],
       [0.09166491],
       [0.8776684 ]], dtype=float32)

In [127]:
predict01 = np.where(pred> 0.5 , 1, 0)
print("======")
print("predict01")
print(predict01)

predict01
[[0]
 [0]
 [0]
 [1]]


In [128]:
predict02 = predict01.flatten()
predict02

array([0, 0, 0, 1])

In [129]:
 %tensorflow_version 1.x

In [130]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import tensorflow as tf
tf.enable_eager_execution()

In [131]:
data = datasets.load_breast_cancer()

In [132]:
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry\n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        worst/largest values) of these features were computed for each image,\n        resulting in 30 features.

In [133]:
X = data.data
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [134]:
X = np.array(X, dtype = 'float32')

X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], dtype=float32)

In [135]:
y = data.target

In [136]:
y = np.array(y, dtype = 'float32')

In [137]:
y = y.reshape(-1, 1)

In [138]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [139]:
y_test

array([[1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],

In [140]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler.fit(X_train)

StandardScaler()

In [141]:
X_train = scaler.transform(X_train)

In [142]:
def sigmoid(h ) :
  return 1 / (1 + np.exp(-h))

In [143]:
#tf.contrib.layers.xavier_initializer()
initializer = tf.contrib.layers.xavier_initializer()

w = tf.Variable(initializer([30, 1]))
w

<tf.Variable 'Variable:0' shape=(30, 1) dtype=float32, numpy=
array([[ 0.26152533],
       [-0.4395585 ],
       [-0.07991752],
       [-0.1816999 ],
       [ 0.35514802],
       [-0.30267996],
       [ 0.07781404],
       [ 0.19753003],
       [-0.07079312],
       [-0.21925291],
       [ 0.37083316],
       [-0.27062297],
       [-0.09772912],
       [-0.39139566],
       [ 0.07629532],
       [ 0.20744157],
       [-0.34269157],
       [ 0.41072994],
       [-0.24496076],
       [-0.32786858],
       [ 0.07081932],
       [ 0.39420825],
       [ 0.22134095],
       [-0.36636445],
       [-0.14957634],
       [-0.35499194],
       [ 0.17096996],
       [-0.09177798],
       [-0.00424564],
       [-0.29404306]], dtype=float32)>

In [144]:
b = tf.Variable(initializer([1]))
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([-1.0972266], dtype=float32)>

In [145]:
hypothesis = tf.matmul(X_train, w) + b
hypothesis

<tf.Tensor: id=395585, shape=(455, 1), dtype=float32, numpy=
array([[-4.99191284e-02],
       [-1.23677385e+00],
       [-2.10459650e-01],
       [-1.88434863e+00],
       [ 3.52526188e-01],
       [-9.35514569e-01],
       [-9.03252363e-02],
       [-3.53384018e-02],
       [-4.25663292e-01],
       [-7.10556626e-01],
       [-1.99966109e+00],
       [-2.68564415e+00],
       [-3.16105628e+00],
       [ 4.26797867e-02],
       [-8.45357537e-01],
       [-2.37858963e+00],
       [-1.85935795e-01],
       [-2.09681749e+00],
       [-1.45324421e+00],
       [-1.04116678e-01],
       [-1.46615863e+00],
       [-1.24665654e+00],
       [-1.25509453e+00],
       [-8.19053650e-01],
       [-1.38305247e+00],
       [-1.21608508e+00],
       [ 5.90425730e-02],
       [-2.07054555e-01],
       [-1.51593685e+00],
       [-9.17930424e-01],
       [-1.87216449e+00],
       [ 3.81737471e-01],
       [-9.79919195e-01],
       [ 1.78763032e-01],
       [-7.76645005e-01],
       [-9.55306053e-01],
   

In [146]:
optimizer = tf.train.AdamOptimizer(0.001)

In [147]:
for step in range(100) :
  with tf.GradientTape() as tape :
    hypothesis = tf.sigmoid(tf.matmul(X_train , w) + b)

    cost = -tf.reduce_mean(y_train * tf.log(hypothesis) + (1 - y_train) * tf.log(1 - hypothesis)) 

    grads = tape.gradient(cost, [w, b])

  optimizer.apply_gradients(grads_and_vars = zip(grads, [w,b]))

  if step % 10 == 0 :
    print("=" * 50)
    print("step : {}, cost : {}, w {}, b{}".format(step, cost.numpy(), w.numpy(), b.numpy()))

step : 0, cost : 0.9741911292076111, w [[ 0.26052535]
 [-0.4405585 ]
 [-0.08091752]
 [-0.1826999 ]
 [ 0.35414803]
 [-0.30367994]
 [ 0.07681404]
 [ 0.19653003]
 [-0.07179312]
 [-0.21825291]
 [ 0.36983317]
 [-0.26962298]
 [-0.09872912]
 [-0.39239565]
 [ 0.07729531]
 [ 0.20644158]
 [-0.34369156]
 [ 0.40972996]
 [-0.24396077]
 [-0.3268686 ]
 [ 0.06981932]
 [ 0.39320827]
 [ 0.22034095]
 [-0.36736444]
 [-0.15057634]
 [-0.35599193]
 [ 0.16996996]
 [-0.09277798]
 [-0.00524564]
 [-0.29504305]], b[-1.0962266]
step : 10, cost : 0.9136314988136292, w [[ 0.25055197]
 [-0.4505248 ]
 [-0.09089033]
 [-0.19267227]
 [ 0.34418467]
 [-0.3136378 ]
 [ 0.06684959]
 [ 0.18656047]
 [-0.08174901]
 [-0.2082481 ]
 [ 0.35986358]
 [-0.2596288 ]
 [-0.1086974 ]
 [-0.402366  ]
 [ 0.08728237]
 [ 0.19655634]
 [-0.35359177]
 [ 0.39976916]
 [-0.23396742]
 [-0.31683668]
 [ 0.05984646]
 [ 0.38323778]
 [ 0.21036883]
 [-0.37733623]
 [-0.16054313]
 [-0.36595172]
 [ 0.16000713]
 [-0.10274736]
 [-0.01521276]
 [-0.30491588]], b[-

In [148]:
X_test = scaler.transform(X_test)
X_test

array([[-0.74676424, -0.11113739, -0.7722409 , ..., -0.8043601 ,
         0.6579971 , -0.76543045],
       [-0.85663545,  0.7483869 , -0.84764045, ..., -0.78964806,
         0.4339004 , -0.20090948],
       [ 1.0534313 ,  0.4176215 ,  1.3087887 , ...,  1.2165011 ,
         0.5582167 ,  2.0367694 ],
       ...,
       [ 0.10403235,  1.9363471 ,  0.18105505, ...,  0.83429086,
         2.1497962 ,  2.8472764 ],
       [-0.8819904 , -0.5583695 , -0.87087166, ..., -0.6352473 ,
         0.15418796, -0.28649455],
       [-0.9496033 , -2.2168553 , -0.9584983 , ..., -1.0641721 ,
        -1.3310683 , -0.38964987]], dtype=float32)

In [149]:
pred = tf.sigmoid(tf.matmul(X_test, w) + b)
pred

<tf.Tensor: id=401981, shape=(114, 1), dtype=float32, numpy=
array([[6.2054509e-01],
       [3.3931196e-01],
       [8.7898970e-03],
       [1.0497308e-01],
       [6.1655426e-01],
       [4.6205786e-01],
       [7.6904893e-04],
       [1.8372935e-01],
       [1.7788887e-02],
       [3.8047463e-02],
       [1.7709491e-01],
       [6.0642105e-01],
       [6.7960209e-01],
       [5.9896111e-03],
       [5.5436492e-01],
       [6.9087684e-01],
       [3.9239022e-01],
       [1.8950006e-01],
       [7.6021093e-01],
       [1.3326564e-01],
       [3.3722758e-01],
       [9.0536654e-02],
       [1.7704442e-01],
       [5.3809702e-01],
       [7.8866422e-02],
       [7.3518717e-01],
       [3.7412345e-01],
       [3.0273849e-01],
       [3.6691302e-01],
       [5.2343154e-01],
       [4.2693138e-02],
       [5.4480404e-01],
       [4.9686909e-01],
       [5.3524625e-01],
       [6.4655006e-01],
       [4.8512888e-01],
       [2.2195533e-01],
       [1.5009221e-01],
       [6.3527465e-01],
   

In [150]:
pred01 = tf.cast(pred > 0.5, dtype = tf.float32)
print("pred01")
print(pred01)

pred01
tf.Tensor(
[[1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]], shape=(114, 1), dtype=float32)


In [151]:
ac01 = tf.equal(pred01, y_test)

In [152]:
ac02 = tf.reduce_mean(tf.cast(ac01, dtype = "float32"))
ac02

<tf.Tensor: id=401989, shape=(), dtype=float32, numpy=0.7368421>

In [153]:
accuracy = ac02
print('accuracy : ', accuracy.numpy())

accuracy :  0.7368421


In [154]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

import tensorflow as tf

In [155]:
model = Sequential()

model.add(Dense(1, input_dim = 30, activation = 'sigmoid'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 1)                 31        
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [156]:
model.compile(loss = 'binary_crossentropy', optimizer = Adam(lr = 0.001), metrics = ['acc'])

In [157]:
model.fit(X_train, y_train, epochs = 1000)

Train on 455 samples
Epoch 1/1000
455/455 [==============================] - 0s 702us/sample - loss: 0.5113 - acc: 0.7451
Epoch 2/1000
455/455 [==============================] - 0s 57us/sample - loss: 0.4475 - acc: 0.8044
Epoch 3/1000
455/455 [==============================] - 0s 70us/sample - loss: 0.3981 - acc: 0.8681
Epoch 4/1000
455/455 [==============================] - 0s 63us/sample - loss: 0.3600 - acc: 0.8879
Epoch 5/1000
455/455 [==============================] - 0s 66us/sample - loss: 0.3298 - acc: 0.9033
Epoch 6/1000
455/455 [==============================] - 0s 69us/sample - loss: 0.3042 - acc: 0.9209
Epoch 7/1000
455/455 [==============================] - 0s 67us/sample - loss: 0.2843 - acc: 0.9253
Epoch 8/1000
455/455 [==============================] - 0s 58us/sample - loss: 0.2669 - acc: 0.9297
Epoch 9/1000
455/455 [==============================] - 0s 60us/sample - loss: 0.2523 - acc: 0.9319
Epoch 10/1000
455/455 [==============================] - 0s 55us/sample - loss

In [158]:
pred = model.predict(X_test)

In [159]:
predict01 = np.where(pred > 0.5 , 1, 0)
print(predict01)

[[1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]]


In [160]:
predict03 = (predict01.flatten() == y_test)

In [161]:
np.sum(predict01.flatten())

69

In [162]:
len(predict03)

114

In [163]:
acc = np.sum(predict01.flatten()) / len(predict03)

In [164]:
acc

0.6052631578947368