## 1. 파이썬 기초 문법
 - 데이터 타입
     - 정수형(int)
     - 실수형(float)
     - 문자형(char)
 - 복합자료형(iterable)

     - 리스트 => 순서, 수정 가능
     - 튜플 => 순서, 수정 불가능
     - 셋 => 중복을 허용하지 않음
     - 딕셔너리 => {KEY : VALUE}
     
## 2. Statement & Function
 - 조건문
     if elif else
     ? :
 - 반복문
     for in
 - 함수
     def
     익명함수 lambda .. 변수 : 조건 : 리턴값
     
#### 삼항연산
 - var <B>val1</B> if condition else <B>val2</B> 

# 라이브러리와 모듈, 패키지

## 모듈
 - 특정 기능들이 구현되어 있는 파이썬 파일(.py)
 - 필요한 파일을 import
 - 파이썬 코드를 논리적으로 묶어서 관리하고 사용할 수 있도록 한 것
 - EX) math.factorial(5) / from math import factorial

## 패키지, 라이브러리
 - 특정 기능과 관련된 여러 모듈을 하나의 폴더에 넣은 것.
 - 파이썬에 기본적으로 설치되는 라이브러리 - stdlib
 - 사용자가 별도의 프로그램을 작성 안함.
 
 - 라이브러리는 특정 기능을 지원하는 모듈 및 함수를 모아놓은 집함
 - 기능에 따라 여러가지 라이브러리가 존재함.
    
### 데이터 사이언스 분야의 패키지..
 - pandas, numpy, matplotlib, scipy, seaborn, statsmodels, scikit-learn, tensorflow
 
### 패키지 활용
 - pip(python install package) : 각종 패키지들을 설치 및 제거, 업데이트 하는 명령어, 주피터 싫랭시 !입력후 실행
 - !pip list
 - !pip upgrade

# Numpy

 - Numeric + Python 의 약자, 수학 및 과학 연산 라이브러리
 - 배열이나 행렬 계산 함수 제공
 - 수열데이터 사용시 용이, 이후에 Pandas에서 DataFrame 형태로 사용함
 - 다차원 배열을 다룰 때 주로 사용.(인공 신경망, 비정형 데이터 처리, 자연어 처리 등)
 - 판다스는 데이터프레임 내의 데이터를 행렬로 처리

In [20]:
import numpy as np

data = [6, 5, 3, 6, 3, 2, 1]

In [28]:
# Numpy Data type (dtype)
arr = np.array(data)
arr.mean()
arr.dtype

dtype('int32')

In [29]:
arr3 = np.array(['A', 'B', 'C'])
arr4 = np.array(['하이', '소리']) # dtype('<U2')

In [35]:
# 2차원 행렬 생성(이중 리스트 사용)

data = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix = np.array(data)
print(type(matrix))
matrix

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
# Matrix 사칙연산
mat1 = np.array([[1,2], [2,3], [19, 30]])
mat2 = np.array([[3,4], [5,6], [7,8]])
m = np.array([1,2,3])
print(mat1 + mat2)
print(mat1 - mat2)
print(mat1 ** 2)

[[ 4  6]
 [ 7  9]
 [26 38]]
[[-2 -2]
 [-3 -3]
 [12 22]]
[[  1   4]
 [  4   9]
 [361 900]]


In [49]:
# 배열의 형태 shape
mat1.shape

(3, 2)

In [57]:
arr3 = np.array([
    [1, 2],
    [3, 4]
])

print(arr3.shape, arr3, end= '\n')

(2, 2) [[1 2]
 [3 4]]


In [66]:
arr4 = np.arange(10)
arr5 = np.arange(1,6)
arr6 = np.arange(1, 10, 2)

In [70]:
arr7 = np.random.randn(10, 5)
arr7

# 평균 0, 표준편차 1의 정규분포 형태를 가진 값을 랜덤으로 산출하는 함수

array([[-0.11314541, -0.93297674, -1.87456653, -0.06720974, -2.50382849],
       [-1.4833217 , -0.87830002, -0.91692206,  1.7641309 ,  0.83965477],
       [-0.19862303,  0.47417123,  0.740451  ,  1.24003272, -0.74268795],
       [-1.00563314, -0.25061223, -1.91733524,  0.54766078,  0.53392028],
       [-0.13829927, -1.24744466,  1.16007154,  0.0510459 ,  1.45679895],
       [-1.83077911, -0.51460872,  0.6476422 ,  0.07836756, -3.38511321],
       [-0.19987344,  0.36702194,  0.71600336,  1.15838037,  0.18320329],
       [ 1.24992511, -0.95062045,  1.17929978,  0.24525108, -0.33151916],
       [-0.7172986 ,  2.15948054,  0.22489322, -1.16868054, -0.13954008],
       [ 0.54645146,  0.78102741,  0.0734096 ,  0.04696563, -0.30908503]])

In [77]:
arr_1 = np.array([1,2,3,4,5])
print(arr_1.dtype)

arr_2 = arr_1.astype(float)
print(arr_2.dtype)

int32
float64


C:\Users\user\AppData\Local\Temp/ipykernel_8576/902003095.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr_2 = arr_1.astype(np.float)


In [80]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr= np.array([[1,2,5], [6,7,8], [9, 10, 15]])
arr.shape

(3, 3)

In [86]:
arr

array([[ 1,  2,  5],
       [ 6,  7,  8],
       [ 9, 10, 15]])

In [87]:
arr[0,0]

1

In [92]:
# [1, 2, 5]
arr[0, :]

array([1, 2, 5])

In [96]:
# [1,6, 9]
arr2 = arr[: , 0]
arr[0:2, :]

array([[1, 2, 5],
       [6, 7, 8]])

In [101]:
# [3, 4, 5]
# arr[:][0] vs arr[:, 0]
arr[:][0] = [3, 4, 5]
arr

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 15]])

In [104]:
arr = np.arange(1, 11).reshape(5, 2)
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [119]:
#영행렬 생성
arr_z = np.zeros((2,2)).astype(int)
arr_z

#항등행렬 생성
arr_l = np.ones((2,2)).astype(int)
arr_l

array([[1, 1],
       [1, 1]])

In [163]:
# array operation
arr1 = np.arange(1, 11).reshape(5, 2) # 사이즈 공유 필요
#arr1.sum()
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [165]:
# axis = 1 인 경우 행 순으로 계산.. 0 인 경우  열을 계산
arr1.sum(axis=1)

array([ 3,  7, 11, 15, 19])

In [123]:
arr1.sum(axis = 0)

array([25, 30])

In [126]:
arr1.mean(axis = 0)

array([5., 6.])

# Pandas
- 데이터 과학에 사용되는 라이브럴리로 데이터 불러오기, 전처리, 통계분석에 사용됨
- Numpy 기반으로 작성된 라이브러리
- Series 형태와 DataFrame 형태가 존재함
- 넘파이 기반이기 때문에 넘파이 전용 함수 사용 가능.

[python_web] https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

- import pandas as pd

## What is Series Data?
- a1 = pd.Series([1,2,3,4,5,6,7])


### random 함수
 - np.random.randn(m, m)  : 가우시안 표준 정규 분포 난수 생성
 - np.random.randint() 균일분포 정수 난수를 생성
 - np.random.rand() : 0 ~ 1 사이의 균일분포 난수 생성


In [128]:
import pandas as pd

In [129]:
a1 = pd.Series([1,2,3,4,5,6,7,11])

In [132]:
a1.sum()
a1.mean()

4.875

In [140]:
s2 = pd.Series(['Kim', 'JIN', "Max"], name = '출석부', index = ['하나', '둘', '셋'])

In [152]:
# Series to Dict
# 각 데이터가 매핑된 형태..

mydict = {
         'name' : 'Kim',
         'age' : 20,
         'gender' : 'male',
         'job' : 'Strudent'
         }

person = pd.Series(mydict, name = '출석부')

In [156]:
# 비교연산자의 특징은 Bool 형태
person[person != 'male']
person[person == 'male']

gender    male
Name: 출석부, dtype: object

In [158]:
#list -> Series
a = pd.Series([2, 3, 4, 5, 6])
# dict -> Seiries
b = pd.Series({'Name' : "JONGwOO"})

### enumerate() 함수는 인덱스랑 값을 같이 출력

In [167]:
grade = pd.Series(['Kim', 'JIN', "Max"], name = '출석부', index = ['하나', '둘', '셋'])

In [172]:
for idx, value in enumerate(grade) :
    print('idx : {}, value: {}'.format(idx, value))
for key, value in grade.items() :
    print(key, value)

idx : 0, value: Kim
idx : 1, value: JIN
idx : 2, value: Max
하나 Kim
둘 JIN
셋 Max


# Pandas DataFrame

- DataFrame ; 엑셀과 같이, 인덱스, 변수(column), 값으로 이루어진 데이터 , idx는 고유값이므로 중복될 수 없음.
- 대용량 데이터를 쉽고 빠르게 다룰수 있음 : 1G ~ 100G
- 다른 시스템과의 연동이 쉽다.
- 넘파이 라이브러리에서 지원하는 수학 및 통계 연산을 그대로 이용할 수 있다.
- 가장 구조적인 데이터 형태로서 직관적이고 설명하기 쉬우며, csv or excel 형태로 저장 가능
- DataFrame은 Series 가 모인 자료구조이다. 이중리스트로 조회한다.


## DataFrame Handling
 - Indexing - 실무에서는 불필요한 Column이 많아 원하는 Column만 추출해 올 필요가 있다.
 
 [python_web] https://paperswithcode.com
 

In [173]:
import pandas as pd

In [180]:
num1 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [181]:
np.array(num1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [182]:
pd.Series(num1)

0    [1, 2, 3]
1    [4, 5, 6]
2    [7, 8, 9]
dtype: object

In [186]:
pd.DataFrame(num1)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [190]:
table1 = [
    ['2021-12-06', 1000, 'False', 'gum'],
    ['2021-12-07', 2000, 'True', 'snack'],
    ['2021-12-08', 3000, 'False', 'beverage'],
    ['2021-12-09', 4000, 'False', 'candy'],
]

In [202]:
df = pd.DataFrame(table1, columns = ['일자', '가격', '구매여부', '제품'])

In [204]:
type(df.columns)
type(df.index)

pandas.core.indexes.range.RangeIndex

KEY 컬럼 / VALUE : 데이터

In [207]:
table2 = {
    '일자' : ['2021-12-06', '2021-12-07', '2021-12-08', '2021-12-09'],
    '가격' : [1000, 3000, 2000, 1000],
    '구매여부' : [False, True, True, True],
    '제품' : ['gum', 'snack', 'beverage', 'gum']
}

In [208]:
df1 = pd.DataFrame(table2)

In [209]:
df1

일자    가격   구매여부        제품
0  2021-12-06  1000  False       gum
1  2021-12-07  3000   True     snack
2  2021-12-08  2000   True  beverage
3  2021-12-09  1000   True       gum

In [211]:
df1.head(2) # 상위 5(2)개를 보겠다.

일자    가격   구매여부     제품
0  2021-12-06  1000  False    gum
1  2021-12-07  3000   True  snack

In [212]:
df1.tail(1) # 하위 n개를 보겠다

일자    가격  구매여부   제품
3  2021-12-09  1000  True  gum

In [221]:
df1.sort_values(by = ['일자', '가격'], ascending = True) # ascending => 오름차순 앞 순서부터 차례로 정렬

일자    가격   구매여부        제품
0  2021-12-06  1000  False       gum
1  2021-12-07  3000   True     snack
2  2021-12-08  2000   True  beverage
3  2021-12-09  1000   True       gum

In [224]:
df1['가격'].mean()
df1['가격'].sum()

7000

In [225]:
df1.describe() # 기초통계량을 제시

가격
count     4.000000
mean   1750.000000
std     957.427108
min    1000.000000
25%    1000.000000
50%    1500.000000
75%    2250.000000
max    3000.000000

In [227]:
df1.describe(include = 'object')

일자   제품
count            4    4
unique           4    3
top     2021-12-06  gum
freq             1    2

In [231]:
df1[['가격', '일자']]

가격          일자
0  1000  2021-12-06
1  3000  2021-12-07
2  2000  2021-12-08
3  1000  2021-12-09

### Indexing 을 위한 location 함수
 - Dataframe.loc[] : 해당 index의 row 데이터를 불러온다. at함수도 같은 기능을 하지만 여러데이터를 불러올 땐 loc가 더 유용.


In [239]:
# location 함수
df1.loc[[0, 1]] 
df1.loc[:]

일자    가격   구매여부        제품
0  2021-12-06  1000  False       gum
1  2021-12-07  3000   True     snack
2  2021-12-08  2000   True  beverage
3  2021-12-09  1000   True       gum

In [242]:
df1.loc[0, '가격'] # df1.loc[행, 렬]

1000

In [247]:
df1['가격'] >= 2000 # 비교연산자

df1[df1['제품'] == 'gum']

일자    가격   구매여부   제품
0  2021-12-06  1000  False  gum
3  2021-12-09  1000   True  gum

In [251]:
df1[df1['제품'].isin(['snack', 'gum'])]

일자    가격   구매여부     제품
0  2021-12-06  1000  False    gum
1  2021-12-07  3000   True  snack
3  2021-12-09  1000   True    gum

In [255]:
data = ['gum', 'snack']
df1[~df1['제품'].isin(data)]

일자    가격  구매여부        제품
2  2021-12-08  2000  True  beverage

In [259]:
df1['환불여부'] = ['정상', '환불', '정상', '환불']
df1

일자    가격   구매여부        제품 환불여부
0  2021-12-06  1000  False       gum   정상
1  2021-12-07  3000   True     snack   환불
2  2021-12-08  2000   True  beverage   정상
3  2021-12-09  1000   True       gum   환불

In [260]:
# 특정 조건에 따른 데이터 생성
condition1 = (df1['제품'] == 'gum') | (df1['환불여부'] == '환불') 

df1.loc[condition1, '관심대상'] = True
df1.loc[~condition1, '관심대상'] = False

In [268]:
df1.drop(0, axis = 0)
df1.drop('관심대상', axis = 1) # axis = 탐색할 축

일자    가격   구매여부        제품 환불여부
0  2021-12-06  1000  False       gum   정상
1  2021-12-07  3000   True     snack   환불
2  2021-12-08  2000   True  beverage   정상
3  2021-12-09  1000   True       gum   환불

In [273]:
cond = ['환불여부', '관심대상']
#df1.drop(cond, axis = 1, inplace = True)

In [281]:
df1['구매여부(replace)'] = df1['구매여부'].replace('True', 0).replace('False', 1)
df1

일자    가격   구매여부        제품  구매여부(replace)
0  2021-12-06  1000  False       gum          False
1  2021-12-07  3000   True     snack           True
2  2021-12-08  2000   True  beverage           True
3  2021-12-09  1000   True       gum           True

In [284]:
# 한글말로 수정
df1['제품(replace)'] = df1['제품'].replace('gum', '껌').replace('snack', '스낵').replace('beverage', '음료')

In [285]:
df1

일자    가격   구매여부        제품  구매여부(replace) 제품(replace)
0  2021-12-06  1000  False       gum          False           껌
1  2021-12-07  3000   True     snack           True          스낵
2  2021-12-08  2000   True  beverage           True          음료
3  2021-12-09  1000   True       gum           True           껌

In [286]:
df3 = pd.DataFrame(table2)

In [287]:
df3

일자    가격   구매여부        제품
0  2021-12-06  1000  False       gum
1  2021-12-07  3000   True     snack
2  2021-12-08  2000   True  beverage
3  2021-12-09  1000   True       gum

# 데이터 불러오기
- pandas를 이용해 csv 혹은 excel 형식의 데이터 파일을 불러올 수 있음
- 필요한 경우에는 데이터 파일 간 병합(join)의 수행이 필요
- read_csv() 명령어를 이용하여 데이털르 불러옴
- 위치를 상대경로로 지정해주어야함 아니면 같은 폴더에 위치


In [301]:
# url_data
url_data = 'http://46.101.230.157/dilan/pandas_tutorial_read.csv'
table1 = pd.read_csv(url_data, delimiter = ';', names = ['datetimes', 'event', 'country', 'userID', 'source', 'topic'])
print(table1.shape)
table1.head()

(1795, 6)


datetimes event    country      userID   source          topic
0  2018-01-01 00:01:01  read  country_7  2458151261      SEO  North America
1  2018-01-01 00:03:20  read  country_7  2458151262      SEO  South America
2  2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
3  2018-01-01 00:04:02  read  country_7  2458151264  AdWords         Europe
4  2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America

## GroupBy, pivot table

- 데이터 분석에 가장 많이 사용되는 함수, 데이터를 특정 항목에 대해 요약 정리
- 월별 매출액 / 항목별 판매량 / 라인 별 불량률 등 원하는 목표 변수에 대한 지표를 직관적으로 확인 가능

- Group By : 항목 별 값의 결과를 Series로
- Pivot Table : 결과를 DataFrame으로



In [302]:
!cd 

C:\Users\user\Desktop\SaltLux\Code


In [329]:
import numpy as np
import pandas as pd

In [330]:
current_path = "C:/Users/user/Desktop/SaltLux/Code/data/store_market_data.csv"

In [331]:
table1 = pd.read_csv('store_market_data.csv')

In [332]:
print(table1.shape)
table1.head()

(705571, 20)


공급일자 요일  공급월  공급주차        회원번호 조합원상태 물품대분류  물품중분류     물품소분류  \
0  2018-01-02  화    1     1   272369856  정상회원    과실     과일        사과   
1  2018-01-02  화    1     1  1506656256  정상회원    채소     버섯     느타리버섯   
2  2018-01-02  화    1     1  1506656256  정상회원   축산물      알       유정란   
3  2018-01-02  화    1     1  1023108864  정상회원    반찬  두부/유부        두부   
4  2018-01-02  화    1     1  1476143616  정상회원    간식      빵  식빵, 식사대용   

                물품명  구매수량 주소-구  주소-동 성별    연령    연령대   구매금액 구매매장  반품_원거래일자  \
0       사과/유(1.5kg)   1.0  수지구  풍덕천동  여  45.0    40대  22207  매장C       NaN   
1       느타리버섯(300g)   1.0  수지구  풍덕천동  여  36.0  30대이하   4977  매장C       NaN   
2  유정란/매장용(10알/국내산)   1.0  수지구  풍덕천동  여  36.0  30대이하   7083  매장C       NaN   
3         연두부(100g)   1.0  수지구  풍덕천동  여  36.0  30대이하    766  매장C       NaN   
4   아침빵(240g/8개)/매장   1.0  수지구  풍덕천동  여  34.0  30대이하   4403  매장C       NaN   

    구매시각  
0  10:04  
1  10:05  
2  10:05  
3  10:08  
4  10:09

In [323]:
table2 = pd.read_csv(current_path)
print(table2.shape)

(705571, 20)


In [333]:
table1.groupby('요일')['구매금액'].mean() # 요일을 인덱스로.. 평균 겂

요일
금    11064.344340
목    10857.069337
수    11062.047300
월    10542.528917
일    10939.249736
토    11046.589839
화    11002.352378
Name: 구매금액, dtype: float64

In [334]:
table1.head()

공급일자 요일  공급월  공급주차        회원번호 조합원상태 물품대분류  물품중분류     물품소분류  \
0  2018-01-02  화    1     1   272369856  정상회원    과실     과일        사과   
1  2018-01-02  화    1     1  1506656256  정상회원    채소     버섯     느타리버섯   
2  2018-01-02  화    1     1  1506656256  정상회원   축산물      알       유정란   
3  2018-01-02  화    1     1  1023108864  정상회원    반찬  두부/유부        두부   
4  2018-01-02  화    1     1  1476143616  정상회원    간식      빵  식빵, 식사대용   

                물품명  구매수량 주소-구  주소-동 성별    연령    연령대   구매금액 구매매장  반품_원거래일자  \
0       사과/유(1.5kg)   1.0  수지구  풍덕천동  여  45.0    40대  22207  매장C       NaN   
1       느타리버섯(300g)   1.0  수지구  풍덕천동  여  36.0  30대이하   4977  매장C       NaN   
2  유정란/매장용(10알/국내산)   1.0  수지구  풍덕천동  여  36.0  30대이하   7083  매장C       NaN   
3         연두부(100g)   1.0  수지구  풍덕천동  여  36.0  30대이하    766  매장C       NaN   
4   아침빵(240g/8개)/매장   1.0  수지구  풍덕천동  여  34.0  30대이하   4403  매장C       NaN   

    구매시각  
0  10:04  
1  10:05  
2  10:05  
3  10:08  
4  10:09

In [336]:
table1.groupby(['요일', '연령대'])['구매금액'].sum()

요일  연령대  
금   30대이하    158434038
    40대      449759043
    50대      319196997
    60대      170808002
    70대이상    117390184
목   30대이하    150301936
    40대      416901325
    50대      293524482
    60대      157682379
    70대이상    112148947
수   30대이하    156665842
    40대      436644537
    50대      298765854
    60대      168640554
    70대이상    100567716
월   30대이하    195332433
    40대      502023099
    50대      306132225
    60대      189428259
    70대이상    112213387
일   30대이하     88129516
    40대      219118519
    50대      162602594
    60대       79819775
    70대이상     41891404
토   30대이하    139605909
    40대      392879470
    50대      315820204
    60대      135737196
    70대이상     92900311
화   30대이하    159659515
    40대      459077946
    50대      324727130
    60대      175776657
    70대이상    104139379
Name: 구매금액, dtype: int64

In [337]:
table1['주소-구'].value_counts(normalize = True)

수지구       0.860027
기타        0.040995
기흥구       0.036481
분당구       0.031912
수원 영통구    0.009754
서울 강남구    0.006138
서울 송파구    0.004014
처인구       0.002618
화성        0.002422
광주        0.002123
중원구       0.001094
수원 장안구    0.000777
수정구       0.000536
수원 팔달구    0.000441
하남        0.000388
수원 권선구    0.000281
Name: 주소-구, dtype: float64

In [352]:
# pivot_table
pd.pivot_table(data= table1, index = '요일', values = '구매금액', columns = '연령대', aggfunc = 'sum').T

요일             금          목          수          월          일          토  \
연령대                                                                       
30대이하  158434038  150301936  156665842  195332433   88129516  139605909   
40대    449759043  416901325  436644537  502023099  219118519  392879470   
50대    319196997  293524482  298765854  306132225  162602594  315820204   
60대    170808002  157682379  168640554  189428259   79819775  135737196   
70대이상  117390184  112148947  100567716  112213387   41891404   92900311   

요일             화  
연령대               
30대이하  159659515  
40대    459077946  
50대    324727130  
60대    175776657  
70대이상  104139379

In [351]:
pd.pivot_table(data= table1, index = '요일', values = '구매금액', aggfunc = ['sum','mean'])

sum          mean
          구매금액          구매금액
요일                          
금   1215650577  11064.344340
목   1130698629  10857.069337
수   1161404346  11062.047300
월   1305186165  10542.528917
일    591561808  10939.249736
토   1076943090  11046.589839
화   1223417575  11002.352378